name: Rust MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout code
        with:
          path: 'wolf-pack'
      - uses: actions/checkout@v2
        name: Checkout cubik
        with:
          repository: 'djandries/cubik'
          path: 'cubik'
          ref: 'master'
          token: ${{ secrets.PAT }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            wolf-pack/target
            ~/.cargo/registry
          key: ${{ runner.os }}-cargo
      - name: Build
        run: cargo build
        working-directory: 'wolf-pack'
