name: Wolf Pack / Rust

on:
  release:
    types: [ created ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#         os: [macos-latest, windows-latest, ubuntu-latest]
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
        with:
          path: 'wolf-pack'
      - uses: actions/checkout@v2
        name: Checkout cubik
        with:
          repository: 'djandries/cubik'
          path: 'cubik'
          ref: 'master'
          token: ${{ secrets.PAT }}
      - name: Install alsa lib
        run: sudo apt-get install libasound2-dev
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            wolf-pack/target
            ~/.cargo/registry
          key: ${{ matrix.os }}-cargo
      - name: Build
        run: cargo build
        working-directory: 'wolf-pack'
      - name: Make Windows installer
        run: makensis /DVERSION=${{ github.event.release.tag_name }} install\win.nsi
        working-directory: 'wolf-pack'
        if: ${{ matrix.os == 'windows-latest' }}
      - name: Upload Windows Installer Asset
        id: upload-release-asset 
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./wolf-pack/target/release/WolfPack-Install.exe
          asset_name: WolfPack-${{ github.ref }}-Install.exe
          asset_content_type: application/vnd.microsoft.portable-executable
